apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  ttlSecondsAfterFinished: 100
  parallelism: 1
  template:
    spec:
      containers:
      - name: migrate-container
        image: alexeino/django_gke:0.4.2
        command: ["/bin/sh","-c"]
        args:
          - |
            python /app/manage.py migrate;
            sql_proxy_pid=$(pgrep cloud_sql_proxy) && kill -INT $sql_proxy_pid;
        envFrom:
          - secretRef:
              name: gkesecret
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=<your_cloud_sql_instance_connectionName>=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-oauth-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      volumes:
        - name: cloudsql-oauth-credentials
          secret:
            secretName: cloudsql-oauth-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir: {}
      restartPolicy: Never
      shareProcessNamespace: true
  backoffLimit: 4