# apiVersion: v1
# kind: Secret
# metadata:
#   name: gkesecret
# type: Opaque
# data:
#     SECRET_KEY: <your_secret_key_encoded>
#     DEBUG: <your_debug_value_encoded>
#     DATABASE_NAME: <your_database_name_encoded> &nbsp; &rarr; *Cloudsql Database Name*
#     DATABASE_USER: <your_database_user_encoded> &nbsp; &rarr; *Cloudsql Database User Name*
#     DATABASE_PASSWORD: <your_database_password_encoded> &nbsp; &rarr; *Cloudsql User Password*